name: Update News

on:
  schedule:
    - cron: '0 4 * * *'  # 07:00 MSK (UTC+3)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install feedparser
      - name: Run news update script
        run: python news.py
      - name: Commit and push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add index.html
          git commit -m "update news" || echo "No changes"
          git push
